# Generated by Django 4.1.4 on 2023-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authpage_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="prefer_title",
            field=models.CharField(default="sample", max_length=200),
            preserve_default=False,
        ),
    ]
