# Generated by Django 4.1.4 on 2023-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage_app', '0002_user_prefer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prefer_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
