# Generated by Django 4.2.4 on 2023-09-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authpage_app", "0003_user_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
