# Generated by Django 4.1.4 on 2023-08-07 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50, verbose_name='글 제목')),
                ('contents', models.CharField(max_length=500, verbose_name='글 내용')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')),
                ('board_name', models.CharField(default='test', max_length=32, verbose_name='게시판 종류')),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('like_users', models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'boardpage_app_post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('postname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardpage_app.post')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
