# Generated by Django 4.1.4 on 2023-05-31 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardpage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 5, 31, 14, 3, 24, 903959)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 5, 31, 14, 3, 24, 903791)),
        ),
    ]
