# Generated by Django 4.2 on 2023-08-11 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0002_post_tag1_post_tag2_post_tag3"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="board_name",
        ),
    ]
