# Generated by Django 4.2 on 2023-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0004_alter_post_tag2_alter_post_tag3"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
