# Generated by Django 4.2 on 2023-06-04 02:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0004_alter_comment_date_alter_post_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="boardpage_app.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 6, 4, 11, 35, 0, 955212)
            ),
        ),
    ]
