# Generated by Django 4.2 on 2023-06-04 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0005_comment_article_alter_comment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="contents",
            new_name="content",
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 6, 4, 12, 12, 33, 853077)
            ),
        ),
    ]
