# Generated by Django 4.2 on 2023-06-04 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0010_rename_content_comment_contents_alter_comment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 6, 4, 13, 34, 0, 258183)
            ),
        ),
    ]
