# Generated by Django 4.2 on 2023-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0012_alter_comment_date_alter_comment_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
