# Generated by Django 4.2 on 2023-06-04 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("boardpage_app", "0014_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="username",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="article",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="contents",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="date",
        ),
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="boardpage_app.post",
            ),
        ),
        migrations.AlterModelTable(
            name="comment",
            table=None,
        ),
    ]
