# Generated by Django 4.1.4 on 2023-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardpage_app', '0015_alter_comment_options_rename_username_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='contents',
            field=models.CharField(default='past', max_length=100),
            preserve_default=False,
        ),
    ]
