# Generated by Django 4.1.4 on 2023-08-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_name', models.CharField(max_length=100)),
                ('L_id', models.CharField(max_length=20)),
                ('L_telnum', models.CharField(max_length=20)),
                ('L_address', models.CharField(max_length=500)),
                ('L_la', models.FloatField()),
                ('L_lo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.CharField(max_length=20)),
                ('P_name', models.CharField(max_length=100)),
                ('P_startdate', models.DateField()),
                ('P_enddate', models.DateField()),
                ('L_name', models.CharField(max_length=100)),
                ('P_Img', models.CharField(max_length=500)),
                ('P_genre', models.CharField(max_length=20)),
                ('P_state', models.CharField(max_length=10)),
                ('P_summary', models.CharField(max_length=2000)),
            ],
        ),
    ]
