# Generated by Django 4.1.4 on 2023-08-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibpage_app', '0002_alter_performance_p_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='L_url',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
