# Generated by Django 4.2 on 2023-08-19 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exhibpage_app", "0003_location_l_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contents", models.CharField(max_length=100)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("like", models.CharField(max_length=20)),
                ("rank", models.CharField(max_length=20)),
                (
                    "P_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exhibpage_app.performance",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
