# Generated by Django 4.2.1 on 2023-08-26 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibpage_app', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
        migrations.AddField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
