# Generated by Django 4.2 on 2023-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibpage_app", "0005_remove_review_like_review_like_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="Perform_id",
            field=models.IntegerField(default=0),
        ),
    ]
